### ISSUE TITLE
Problem in dependent projects with FetchContent approach

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgFramework#10]
At https://github.com/geefr/vsgvr/issues/12 a problem was reported with vsg dependent packages with the change to FetchContent, which requires a change in finding vsg:

from
```
find_package(vsg REQUIRED)
```
to
```
find_package(vsg)
```
The project maintainer believes that such a change should not be required in dependent packages, see https://github.com/geefr/vsgvr/issues/12#issuecomment-1277396973

**Comment by robertosfield** [comment]
This looks to be a CMake issue.  I spent many many hours trying to get around it.  Feel free to spend your own time on finding a solution.  I'm closing this Issue as I've done everything I can to try and avoid the problem I called for others to help and no-one was able to find a solution.
