### ISSUE TITLE
No cmake build targets to clean builds from components

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/vsgFramework#2]
I have created a build of the vsg framework. After the build, I wanted to clean up all the files created, but did not find a build target to perform this step. Using `cmake --build . --target clean` did not perform this. Instead, you have to go into each build directory under src and call `cmake --build . --target clean`.
It would be helpful if there was a corresponding command to simplify this often needed step.

**Comment by rhabacker** [comment]
This has been fixed with #3.

**Comment by robertosfield** [comment]
Closing as your  PR  looks to have resolved this :-) #3
