### ISSUE TITLE
Cache error on build in Windows

### ISSUE THREAD

**Issue by sbrkopac** [vsg-dev/vsgFramework#5]
When building I get the following [errors](https://github.com/vsg-dev/vsgFramework/files/8126782/vsgFrameworkBuild.txt). Doesn't look like they are critical errors as some parts of VSG get built.

My testing was spurred from this thread: https://groups.google.com/g/vsg-users/c/VSMZFJdQFAM

**Comment by robertosfield** [comment]
@sbrkopac I've now merged with the respective masters the FetchContent support into the various VSG projects so vsgFramework should work out of the box using FetchContent.  It builds fine for me under Linux, but would love to know the current status under Windows.  Do the above issues still persist?

**Comment by ahoarau** [comment]
@robertosfield The configure step fails on windows:
![image](https://user-images.githubusercontent.com/703240/196999919-e984db73-ef43-4d94-af45-203ea46c7505.png)

**Comment by robertosfield** [comment]
Do you have OpenSceneGraph installed on your system?  If you want to build osg2vsg then this is a pre-requisite.

What happens when you disable to build of osg2vsg via CMake?

**Comment by ahoarau** [comment]
It works ! It would be great to have the default configuration being **without** any external library - listing all cmake options in the file itself does not come naturally for some people

**Comment by robertosfield** [comment]
On Fri, 21 Oct 2022 at 11:05, Antoine Hoarau ***@***.***>
wrote:

> It works ! It would be great to have the default configuration being
> *without* any external library - listing all cmake options in the file
> itself does not come naturally for some people
>
> vsgFramework has been experimental so far - it's been used to shake down
the VSG and other component libraries when using with submodules and
FetchContent and to prove the concept of building components together.

vsgFramework has not yet been refined in its own right, enabling more
components that would be appropriate by default is one area.  I think
adding checks for dependencies like OpenSceneGraph before enabling osg2vsg
might be one thing to add.

However, in the end it's a template for others to use/learn from so they
can see how to use CMake to pull in component libraries.  It can be used as
a template so developers can use it for their own versions easily.  Long
term I see vsgFramework as a starting place for developers that wish to
build component libraries.  Other users will prefer to build things in
other ways and that's fine.

**Comment by ahoarau** [comment]
> vsgFramework has not yet been refined in its own right, enabling more
components that would be appropriate by default is one area.  I think
adding checks for dependencies like OpenSceneGraph before enabling osg2vsg
might be one thing to add.

The deterministic behavior of having something at ON fail when the dep is not found is better IMO. A message listing the options at the beginning of the cmake configuration could be useful though + when the dep is not found, issue a readable message (at least better than the default cmake error that confuses people).
That would reconciliate first-users (easy/fast first build) and package managers (deterministic builds).

> However, in the end it's a template for others to use/learn from so they
can see how to use CMake to pull in component libraries.  It can be used as
a template so developers can use it for their own versions easily.  Long
term I see vsgFramework as a starting place for developers that wish to
build component libraries.  Other users will prefer to build things in
other ways and that's fine.

That is a good place to start dev with vsg

**Comment by robertosfield** [comment]
I have made the compile of osg2vsg dependent of a find_package(OpenSceneGraph QUIET) being successful so we shouldn't see build errors when external dependencies aren't found.  The change is in vsgFramework master, with commit : 61b39e3577daf0a0459e975fa61b5748a42b933c
